### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by allewwaly** [chwress/salad#1]
during the use of salad, it came to error "Segmentation fault (core dumped)" when I tried to run the example at http://www.mlsec.org/salad/example2.html. The packages is installed according to the Debian/Ubuntu packages of http://www.mlsec.org/salad/install.html. And on windows the archive format is not supported. So what might be the problem then?

**Comment by chwress** [comment]
What OS are you running exactly?

**Comment by allewwaly** [comment]
Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic x86_64)

**Comment by allewwaly** [comment]
I've also tried it on ubuntu 12.04 LTS with  3.2.67-23-generic x86_64 kernel. It repeated the error. And when I removed the "--input-format archive" parameter, the error disappears. But what I want to analyze is a zip file while the default format seems to be lines.

**Comment by allewwaly** [comment]
While building from the source, it turns out to be not support with archive or files mode.

~$ salad inspect --input ex2-train.zip --input-format archive --ngram-len 3 --ngram-delim "" --output "ex2.out"
[W] Illegal input type 'archive', using 'files' instead
[_] Input: ex2-train.zip (files mode)
[_] Output: ex2.out
[!] Input mode 'files' is not yet implemented.
[!] Bye!

**Comment by chwress** [comment]
I can confirm the segmentation fault and I'm going to investigate the issue.

**Comment by chwress** [comment]
Okay, for the time being please build salad from source with -DGROUPED_INPUT=OFF
(libarchive support in turn needs -DUSE_ARCHIVES=ON)

**Comment by chwress** [comment]
I also adapted the debian/ ubuntu packages on launchpad. The actual issue will be fixed with the upcoming version of salad, which already is in the pipeline.

**Comment by allewwaly** [comment]
I've tried the new one and problem gone. Thx
